program = _{ SOI ~ "\n"* ~ (stmt ~ "\n"+) * ~ stmt? ~ EOI }

stmt = _{ expr }

expr = {
    binaryExpr
    | string
    | terms
}

binaryExpr = { terms ~ verb ~ expr }

terms = { term+ }

term = _{ integer | "(" ~ expr ~ ")" }

verb = {
  "+"  | "*" | "-" | "/"
}

integer = @{ "-"? ~ ASCII_DIGIT+ }

string = @{ "'" ~ ( "''" | (!"'" ~ ANY) )* ~ "'" }

WHITESPACE = _{ " " | "\t" }

COMMENT = _{ "NB." ~ (!"\n" ~ ANY)* }